name: test_dbt
version: 1.0.0
config-version: 2
profile: test_dbt
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  test_dbt:
    +materialized: view
